const products = [
  {
    _id: '1',
    name: '16-inch MacBook Pro (2023)',
    image: '/images/appleGaming.png',
    description: "For ultimate Mac gaming, there's nothing better than the third-generation 16-inch MacBook Pro (2023).This model offers an M2 Pro or M2 Max SoC with up to 96GB of unified memory and 8TB of SSD storage.",
    brand: 'Apple',
    category: 'Gaming Laptop',
    price: 2500,
    countInStock: 20,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: '2',
    name: 'MSI-Vector 15.6" 165hz',
    image: '/images/applegaming2.jpeg',
    description:
      ' Intel Core i7HX - 32GB Memory - NVIDIA GeForce RTX 3070 Ti - 1TB SSD - Black',
    brand: 'Apple',
    category: 'Gaming Laptop',
    price: 2069.99,
    countInStock: 9,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: '3',
    name: 'HP ENVY x360',
    image: '/images/hp2in1.png',
    description:
      'Windows 11 HomeIntel® Core™ i5-1235U (up to 4.4 GHz, 12 MB L3 cache, 10 cores, 12 threads) + Intel® Iris® Xe Graphics8 GB DDR4-3200 SDRAM (2 X 4 GB)256 GB PCIe® NVMe™ M.2 SSD',
    brand: 'hp',
    category: '2-in-1',
    price: 849.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Inspiron 14 2-in-1 Laptop',
    image: '/images/dell2in1.avif',
    description:
      '14-inch 2-in-1 laptop designed to bring your world closer. Features a 4-sided narrow border and the latest 11th Generation Intel® Core™ processors.',
    brand: 'dell',
    category: '2-in-1',
    price: 399.99,
    countInStock: 10,
    rating: 4.8,
    numReviews: 20,
  },
  {
    _id: '5',
    name: 'Latitude 5530 Laptop',
    image: '/images/dellBussines.avif',
    description:
      '15.6" FHD Display, 12th Gen Intel Core i5-1235U, 16GB RAM, 512GB SSD, Webcam, HDMI, Thunderbolt 4, Backlit Keyboard, Wi-Fi 6, Windows 11 Pro, Silver',
    brand: 'dell',
    category: 'bussines laptop',
    price: 1079.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 7,
  },
  {
    _id: '6',
    name: 'HP DRAGONFLY FOLIO',
    image: '/images/hpBUssines.png',
    description:
      'HP Dragonfly Folio 13.5 inch G3 2-in-1 Notebook PC - Wolf Pro Security Edition',
    brand: 'hp',
    category: 'bussines laptop',
    price: 2749,
    countInStock: 2,
    rating: 4,
    numReviews: 2,
  },
]

export default products
